# Generated by Django 2.2 on 2019-04-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInfo',
            new_name='BookInf',
        ),
    ]
