# Generated by Django 2.2 on 2019-05-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tparent',
            },
        ),
        migrations.CreateModel(
            name='TeChildModel',
            fields=[
                ('teparentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ttttt.TeParentModel')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tchild',
            },
            bases=('ttttt.teparentmodel',),
        ),
    ]
