# Generated by Django 2.2 on 2019-05-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'test_parent',
            },
        ),
        migrations.CreateModel(
            name='TestChildModel',
            fields=[
                ('testparentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ttttt.TestParentModel')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'test_child',
            },
            bases=('ttttt.testparentmodel',),
        ),
    ]
